### ISSUE TITLE
Anti-correlation slashing penalties should ideally work on a per-committee basis

### ISSUE THREAD

**Issue by vbuterin** [ethereum/consensus-specs#1376]
If a committee publishes a bad crosslink, ideally we would want every member of the committee that participated to be heavily penalized and even lose their entire deposit (as the probability that honest validators in the same committee would have a bug at the same time is astronomically tiny, and the collective failure of a committee caused great harm).

However, the current anti-correlation penalty structure only increases penalties in response to a significant fraction of _all_ validators being slashed.

Unfortunately, because committees get reshuffled so frequently, there is no easy way to fix this. But we should still flag this as something to think about and try to improve.

**Comment by dankrad** [comment]
Would it work to add a second kind of slashing for "really bad" failures like this, that could be invoked on a crosslink? Of course, it would be necessary that it can be applied to slashed validator while waiting for withdrawal.

**Comment by vbuterin** [comment]
One proposal I have is to remove the current collective penalty scheme, and instead only rely on a per-committee anti-correlation slashing mechanism (if a large portion of all validators misbehave, generally a large portion of all committees will misbehave). Then the mechanism would work as follows: you can submit an epoch and seed to generate a committee (or for more security a historical Merkle branch proving that it was a committee), and if you can show that M of N members of the committee have been slashed, you increase every member's penalty to M/N (if any specific member's penalty was already higher than M/N, it stays unchanged).

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.

**Comment by hwwhww** [comment]
closing due to outdated
