### ISSUE TITLE
Exit fee

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#1521]
Taken from the previous Phase 0 state transition checklist in #1054 

> (post-freeze discussion) Exit fee: See #850 (comment).

I'm inclined to _not_ add this for Phase 0 to reduce changes to the near-final spec.
Can be revisited in Phase 1+

CC: @JustinDrake @vbuterin

**Comment by JustinDrake** [comment]
> I'm inclined to not add this for Phase 0

Agreed :)

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.

**Comment by Nouri11190** [comment]
###Checklist

**Comment by Nouri11190** [comment]
###general checklist
