### ISSUE TITLE
[SSZ]  Are Lists limited to 0 values legal SSZ types?

### ISSUE THREAD

**Issue by saltiniroberto** [ethereum/consensus-specs#1863]
List types limited to 0 values, i.e. `List[type, 0]`, are not included in the list of [illegal types in the SSZ specification](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#illegal-types).

However, [line 177 of the py-ssz reference implementation](https://github.com/ethereum/py-ssz/blob/master/ssz/sedes/basic.py#L177), rules out LIst types limited to 0 values by requiring that the maximum length of homogenous composites must be at least 1.

**Comment by djrtwo** [comment]
I don't think these need to be strictly illegal, and in fact we used to have a type that was set to length `0` because it was essentially "disabled". 

Using it as a "feature flag" of sorts is the main use case I can currently think of

**Comment by protolambda** [comment]
- 0-length vectors are illegal. (same for containers)
- 0-limit lists are legal.

The reasoning for the fixed-length types here is that fixed-length types do not have an offset if a dynamic type has a collection of them. Making it impossible to say how many there are `scope / element_size = N / 0` case here.

However, lists will ALWAYS have an offset if any type wraps them, because they couldn't be presented otherwise (Well, except a list at top-most level type, which has a natural scope by input-length, e.g. a byte list doesn't have a length-encoding envelop in SSZ).

Besides, it is a previously used feature of configuring the lists of block-operations in the beacon block to have a 0 limit, to disable the use of that operation. Previously used in transfers. And currently we are considering disabling slashings in some testnets, as a fun way to stress the networks by publishing validator keys, and having everyone sign arbitrary things without retribution.

**Comment by hwwhww** [comment]
I think the spec is correct for flexible configuration as @protolambda mentioned, and py-ecc should be changed to follow the spec definition.

Opened an issue https://github.com/ethereum/py-ssz/issues/116

**Comment by protolambda** [comment]
I'm going to revisit the "new" (no changes, but more details) SSZ spec draft, and work on tests for a lot of these invalid cases. :+1:

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
