### ISSUE TITLE
Validating MAXIMUM_GOSSIP_CLOCK_DISPARITY

### ISSUE THREAD

**Issue by jrhea** [ethereum/consensus-specs#1936]
The phase 0 networking spec declares a constant `MAXIMUM_GOSSIP_CLOCK_DISPARITY` and sets it to 500ms.  The design rationale portion of the networking spec mentions that 500ms is currently a placeholder and will be tuned based on testnet observations.  How do we plan on validating this constant?

IIRC, @arnetheduck mentioned needing to lower the value (making it more negative) in order to improve performance, but provided the disclaimer that it was based on anecdotal evidence.

In my limited observation, I haven't seen any blocks arriving sooner than 500 milliseconds prior to the slot.  Below is a plot from my post on [block propagation analysis](https://ethresear.ch/t/packetology-eth2-testnet-block-propagation-analysis/7561):

![block-arrival](https://user-images.githubusercontent.com/5555162/85751658-614b5080-b6d0-11ea-8e5e-538c50f25113.png)

This plot was generated from 23,910 slots worth of blocks received.  It should be noted that the network agent that collected the data **does not** filter out blocks arriving too soon.  You can see that all blocks are within the `MAXIMUM_GOSSIP_CLOCK_DISPARITY`; however, this just reflects machine's view of time relative to the peers sending the block.

Does anyone have an intuition on how this constant should be validated?  @ericsson49 might have some insight given his work on clock sync methodologies.

**Comment by jrhea** [comment]
I imagine that the methodology used for synchronizing clocks will have some part in deciding the appropriate value for `MAXIMUM_GOSSIP_CLOCK_DISPARITY` and this discussion could easily spiral into discussion methods for dealing with time drift.  As a result, I suggest that we limit the scope of this debate by assuming Phase 0 will rely soley on NTP.  Perhaps this will provide some reasonable starting point when speculating about resolution, slewing, etc and allow us to focus more on how this constant could impact consensus (we can always circle back this when things change).

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
