### ISSUE TITLE
Add gossip validation for attestation LMD vote + FFG vote consistency

### ISSUE THREAD

**Issue by lsankar4033** [ethereum/consensus-specs#2002]
In fork-choice, there's a check that the LMD vote of an attestation is a descendent of the attestation's target (see https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/fork-choice.md#validate_on_attestation following the comment `#LMD vote must be consistent with FFG vote target`)

I propose adding this to the gossip validation to further filter out noise: https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/p2p-interface.md#beacon_attestation_subnet_id

**Comment by djrtwo** [comment]
agree!

We do prevent old head votes from being gossiped (with the slot range checks) but without the head-slot/ffg-epoch consistency check, an “old” (but invalid) ffg vote can be gossiped. Depending on how conditions are written in the client, this could potentially cause an old and unexpected state lookup.

Consistency here seems valuable

**Comment by djrtwo** [comment]
I’m not certain if we absolutely need the consistency check, but it might be worth adding regardless.

Due to #2001, the depth of the `get_ancestor` call is bound so the check should be cheap, but due to the limit of attestations as one per val per epoch, inconsistency here is "expensive" for a validator.

I suppose that if it is after _"The block being voted for (attestation.data.beacon_block_root) passes validation"_ then the chain being voted on is known and the ancestor consistency should be cheap.

Want to sanity check before we add forkchoice lookups in our most frequently gossiped message type: @protolambda what is the cost of an ancestor lookup in most fork choice implementations? Is it constant (especially when in bound slot ranges -- an epoch), or is it `log(N)` or `N`?

**Comment by protolambda** [comment]
In proto-array, `get_ancestor` is avoided by making the justification logic stateful in the array and related optimized batched tracker of last messages.

Checking subtrees if you already have the two roots of the nodes you compare, is constant time. Since you get the best-descendant of both nodes in constant time, and just compare them.

The other way around, searching for a previous node in the chain at a given slot, is not optimized. What you need to do is change get_ancestor, to use the existing optimized data. I think it would be something like:
- lookup proto-array node by target block root (constant time, minus some root->pointer dict costs)
- lookup proto-array node of attestation block root (same complexity as above)
- get best descendant proto-array-index of both nodes (constant time, just an attribute of the node)
- simply compare. If matching: attestation block root is a child of the target block root

**Comment by djrtwo** [comment]
So in this case, we have beacon block root `A` and target block root `T`
At the proposed condition, block `A` would be known and validated. So the check would be adding a constant time lookup of the target and a constant decedent lookup of `A` and `T`. 

So it is _safe_ to add the condition so probably not much reason not to

**Comment by lsankar4033** [comment]
> Due to #2001, the depth of the `get_ancestor` call is bound so the check should be cheap, but due to the limit of attestations as one per val per epoch, inconsistency here is "expensive" for a validator.
> 
> I suppose that if it is after _"The block being voted for (attestation.data.beacon_block_root) passes validation"_ then the chain being voted on is known and the ancestor consistency should be cheap.

Is there a notion of expected precedence in gossip validation checks? If not, a client implementing the checks in the wrong order still seems vulnerable to an expensive `get_ancestor`

**Comment by lsankar4033** [comment]
It seems like there is in fact precedence of validations, based on the order they appear in the p2p spec. That wasn't obvious to me on first reading; perhaps it's worth adding a line to the spec saying as much.

**Comment by dapplion** [comment]
Fixed by https://github.com/ethereum/consensus-specs/pull/2001
