### ISSUE TITLE
Add `reveal_deadline_setting` for test generation

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#2015]
Replace #1974

## Issue
For some current phase 0 test cases, the phase 1 custody-reveal-deadlines-slashing is severe if we make `state` forward for a large number of epochs. To fix it naively, it requires adding custody reveals to these tests, which would create large computation overhead and make the simple test generators verbose.

## Detailed description
(copied from #1974)
For example, [`test_process_custody_slashing.py::test_many_epochs_custody`](https://github.com/ethereum/eth2.0-specs/blob/8a2132e65df19643e7c10be93be5451e4eb501aa/tests/core/pyspec/eth2spec/test/phase1/block_processing/test_process_custody_slashing.py#L126) calls [transition_to(spec, state, state.slot + spec.SLOTS_PER_EPOCH * (spec.EPOCHS_PER_CUSTODY_PERIOD - 1))
](https://github.com/ethereum/eth2.0-specs/blob/8a2132e65df19643e7c10be93be5451e4eb501aa/tests/core/pyspec/eth2spec/test/phase1/block_processing/test_process_custody_slashing.py#L95), which would trigger **the epoch processing**. Some validators may get slashed in `process_reveal_deadlines`.

And when we run `process_custody_slashing`, it checks `assert is_slashable_validator(whistleblower, get_current_epoch(state))` and `assert is_slashable_validator(malefactor, get_current_epoch(state))`. The whistleblower and malefactor may have been slashed by `process_reveal_deadlines`, which is not this test case aim to do.

## Proposed solution
Thanks to @djrtwo @dankrad @protolambda for discussing with me. 🙂 

Similar to how we handle BLS, we can disable the custody reveal deadline for these test cases optionally.

- For the running `pytest`: add a pytest option `--disable-reveal-deadline` to flag that it's disabled.
- For the test generator: add meta key-pair `reveal_deadline_setting: int`, where `0` is enabled and `1` is disabled.

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
