### ISSUE TITLE
Suggestion: Limit deposit_count to be less than MAX_DEPOSIT_COUNT

### ISSUE THREAD

**Issue by montyly** [ethereum/consensus-specs#2025]
Hi,

The deposit contract limits the number of deposits to be less than [`MAX_DEPOSIT_COUNT`](https://github.com/ethereum/eth2.0-specs/blob/f2440451919d4d7516903ec2646e7a00e12be1b7/solidity_deposit_contract/deposit_contract.sol#L66-L67). The eth 2.0 spec does not contain such a limit. As a result, the specification allows for states that are not possible from the deposit contract.

Realistically speaking, this divergence will not happen. However, it might be worth to consider adding the invariant `state.eth1_data.deposit_count < MAX_DEPOSIT_COUNT` to the spec. It would prevent issues for the formalization of the protocol, and additionally prevent integer-related bugs for clients implementations.

For example, we found an issue during the nimbus security review that can be triggered if an attacker proposes a malicious state with a `state.eth1_data.deposit_count` really large (https://github.com/status-im/nim-beacon-chain/issues/1544). Limiting `deposit_count` at the specification level would reduce the likelihood of such issues.

I think that one way to add it would be to check for `state.eth1_data.deposit_count < MAX_DEPOSIT_COUNT` in [`process_operations`](https://github.com/ethereum/eth2.0-specs/blob/f6da7323fe814cc76a08c0e1bca1dbdee3c988af/specs/phase0/beacon-chain.md#operations).

**Comment by djrtwo** [comment]
So this shows up in the spec via `DEPOSIT_CONTRACT_TREE_DEPTH`. It is the natural limit of such a tree (`2**DEPOSIT_CONTRACT_TREE_DEPTH` leaves).

Through what means can an attacker "proposes a malicious state"?

The spec generally does not have self consistency checks within the operation processing (as you recommend). Instead it has transition validations to ensure that the operations acting upon the state cannot mutate it in invalid ways.

The only way this state can be achieved through transitions is >50% validators agreeing to an invalid `eth1data` vote. Following the standard spec  practices, a condition on `block.body.eth1data.deposit_count < MAX_DEPOSIT_COUNT` would be more appropriate. That said, we already have an incredibly strong assumption on `eth1data` not being corrupted. If it could be corrupted, an attacker could just put in an invalid `eth1data.deposit_root` which would prevent any new block from being able to be formed due to lack of deposits available
