### ISSUE TITLE
Bump version to discv5.1

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#2059]
As discussed on last weeks networking call, we decided to bump discovery up to [version 5.1](https://github.com/ethereum/devp2p/pull/157).

What is the state of language implementations? -- Please reply with `not_started`, `in_progress`, `complete` and provide any relevant links to issues/PRs

| Language | Status | Links |
| - | - | - |
| Java | `in_progress` | https://github.com/PegaSysEng/discovery/pull/72 |
| Rust | `complete` (need interop testing) | https://github.com/sigp/lighthouse/issues/1605 |
| Nim | `in_progress` | https://github.com/status-im/nim-beacon-chain/issues/1649  |
| Go | `complete` (reference impl) | https://github.com/ethereum/devp2p/pull/157 |

_Note, this is incompatible with with the current version deployed on Medalla. To be determined if/how we upgrade Medalla, but we intend to use this on mainnet._

**Comment by ajsutton** [comment]
Teku: not_started https://github.com/PegaSysEng/teku/issues/2797

**Comment by AgeManning** [comment]
Lighthouse has started. This issue will be marked complete once it's integrated into Lighthouse: https://github.com/sigp/lighthouse/issues/1605

In regards to updating. If we update one of the current bootnodes to 5.1, then 5.1 nodes can bootstrap. And as Lighthouse clients update to 5.1, when they restart they will re-inject past known ENR's into the 5.1 routing table, essentially joining the DHT's, I imagine.

**Comment by kdeme** [comment]
Nimbus has just started, so in_progress. Tracking issue: https://github.com/status-im/nim-beacon-chain/issues/1649

**Comment by Nashatyrev** [comment]
Teku has also started: https://github.com/PegaSysEng/discovery/pull/72

**Comment by AgeManning** [comment]
We have finished our implementation, pending some interop testing.

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
