### ISSUE TITLE
Merge side-effect: duplicate execution state-root concern

### ISSUE THREAD

**Issue by protolambda** [ethereum/consensus-specs#2389]
As far as I'm aware, the state-root in the eth1 block structure is of a MPT of the world-state, a tree of accounts, no data that changes regardless of block contents, with the exception of the block-reward. @djrtwo was [asking](https://github.com/ethereum/eth2.0-specs/pull/2380#discussion_r626969907) about a repeat of the state root in PR #2380 and pointed out [EIP 210](https://eips.ethereum.org/EIPS/eip-210) (block hash history) as something that could touch the state unconditionally (but this EIP isn't actually deployed on mainnet)

With the Merge transition to Eth2, we get a fun new edge-case, due to the move of block-rewards from execution layer (block coinbase) to consensus layer (proposer reward), the tree can stay completely untouched if there are no transactions in the block.

Questions:
- Is this indeed the case, or is there some additional content in the tree of this state-root?
- Is this tested in Eth1 / future execution engine?
- Are there other ethereum forks that have live examples of duplicate state roots, due to different block reward approach and empty blocks? Maybe a PoA testnet?

Tracking:
- [ ] Add test case for Merge with multiple beacon blocks, but with the same state-root in the execution-payload, in eth2 consensus tests.

**Comment by mkalinin** [comment]
We have been discussing this side-effect recently during one of the merge calls. It's been said that Clique also tends to have `state_root` unchanged in case if block has no transactions. As a result, a good example of Ethereum network with duplicated state roots is Rinkeby, look at its earliest blocks: [#1](https://rinkeby.etherscan.io/block/1) and [#2](https://rinkeby.etherscan.io/block/2). This is also the case for the merge testnets.

Related edge case we get is two beacon blocks point to identical execution blocks (the same block from execution engine perspective) as a result of forking. But as long as this case is processed correctly, i.e. execution block stays valid if imported the second time and stays in the canonical chain even if the second beacon block is orphaned, I think we're OK with that.

**Comment by mkalinin** [comment]
I think we should also take the fact that state trie node is immutable and is either removed entirely or persisted by the canonical chain. IMO, it makes it easier to reason about this edge. The case when a block is dereferenced and removed from the storage should be analysed, in particular, client must not remove the state or a part of it if there is another reference to it from the other block. 

From what I know, state pruning algorithms must not remove state nodes that persisted in the canonical chain, because block execution from a fork might insert the same trie nodes as the canonical blocks did. So, when orphaned trie nodes are removed their persistence in the canonical chain is taken in account. These algorithms must either support a ref counting or some alternative technique to handle these cases.

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.

**Comment by mkalinin** [comment]
It worth mentioning that https://github.com/ethereum/eth2.0-specs/pull/2479 (`difficulty = randao_mix`) makes the situation when two beacon blocks referencing the same execution block no longer the case
