### ISSUE TITLE
P2P: Nodes operating behind a NAT, or otherwise undialable by default [...] MUST have their infrastructure configured to enable inbound traffic 

### ISSUE THREAD

**Issue by xanoni** [ethereum/consensus-specs#2549]
I saw the below in the Phase 0 networking spec. Is this still true in practice / do nodes honor it, and if not, is that a problem?

> All listening endpoints must be publicly dialable, and thus not rely on libp2p circuit relay, AutoNAT, or AutoRelay facilities. (Usage of circuit relay, AutoNAT, or AutoRelay will be specifically re-examined soon.)
> 
> Nodes operating behind a NAT, or otherwise undialable by default (e.g. container runtime, firewall, etc.), **MUST have their infrastructure configured to enable inbound traffic on the announced public listening endpoint.**

**Comment by ajsutton** [comment]
There are a lot of nodes that don't follow this and it's not ideal but not causing major issues. If the number of nodes with open ports is low enough it has two risks:

1. The efficiency of the network is reduced - nodes will find it hard to find peers because the few that can be connected to are full, and everything has to route through those nodes.
2. The nodes with open ports become a centralisation risk and, if there are few enough of them, become a possible point of censorship.  Plus all the attacks which require splitting the network become significantly easier.

**Comment by xanoni** [comment]
Yes, that's what I assumed. I was just surprised that it's specified as "MUST have xyz" but in practice nobody cares. Well, that's how life goes.

**Comment by dapplion** [comment]
Maybe the spec should list the consequences (i.e. attacks it enables) of not opening ports in an effort to give more weight to the MUST
