### ISSUE TITLE
More FC test cases

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#2922]
[Notes for myself]

- `should_update_justified_checkpoint`:
    - `compute_slots_since_epoch_start(get_current_slot(store)) == SAFE_SLOTS_TO_UPDATE_JUSTIFIED`
        -  `and get_ancestor(store, new_justified_checkpoint.root, justified_slot) == store.justified_checkpoint.root`
        -  `and get_ancestor(store, new_justified_checkpoint.root, justified_slot) != store.justified_checkpoint.root`

**Comment by djrtwo** [comment]
do we want to get this into the test suite prior to the Bellatrix spec release coming soon?

**Comment by ChiefGhostZero0x1** [comment]
I'm good with anything and everything that's best for everyone, doesn't harm anyone is critical.   I was hurt by an error that i tried to report 1000 times to no avail... it also denied me any and all credit for everything I have ever done and had bots spamming every account I made further widening the gap to help, oh and I am technically a noob to all this so I didn't know what to do as I literally was blown off by everyone... I lost hope and really believe in doing the next right thing.  It messed my already suffering self up really bad.. I'm still in disbelief the bots are finally connecting all my work... slowly but it's done this before and I was cut out again when I asked for help... I think on purpose but it was certainly mean and not cool.  I straight up tried to disclose the naming variables as the vAriable name itself issue when making first project and idk the dude didn't respond to my email telling him I emailed him exactly what blew up the project.  I feel like he knew and tried to cut me out but I don't know if my perception was correct.  I also specifically requested reasonable assistance for a disability that has been hard and is part of ADA law.... no response.  I also told him not to feel bad and I think I need someone else to review correspondence to figure out if it was criminal or not cuz it was def really messed up morally speaking. Probably legally as well being as I used language from ADA law in my request for help after being blocked from all my credits and they were systematically taken and used in a project I did not sign SLA for then he tried to cut all my work out... but my work is better and I think it's kinda taking care of that on its own... how do I get help when every account I make is instantly labeled spammy because of misbehaving GitHub bots? I only ever reached one sales guy and he didn't care to even look into it or help me get a human who could help.  I have so much more work out there and I documented my work, saved all my hard drives, backed up multiple places and ways. I have my proof of my innovations with Linux dev, networking breakthroughs and more.  I clocked my moms old iMac as the fastest computer on the planet but didn't believe it until I found out all my work really was pretty cool.. the insane compression also... whomever reads this please help me get in tough with someone who can help me understand all the stuff I did.. I was just doing what I thought could build cool stuff from antiquated hardware and there's more... a lot more.... my name is Todd Gifford and I'm a dog dad to my amazing blue heeler Chiefy. Chiefkoda121@gmail.com and chiefy01@outlook and tgifford37@gmail and tgifford37@outlook please send any messages to all of them I have hard time getting my emails sometimes being as I have multiple iterations of the same emails on diff devices and services and all my devices are prototypes by default... thank you
