### ISSUE TITLE
capella loop limit when exceeds validator length

### ISSUE THREAD

**Issue by rolfyone** [ethereum/consensus-specs#3166]
Potentially a case that could be a reftest:

 - network config has 16k validators
 - validator minimum is 5k (or importantly anything less than the bound for withdrawals scan)

When the scan for withdrawals happens, the limit is actually a min of the length of validators vs. the sweep length, and importantly, the ending validator key is going to determine if there's a chain split (if a client stops once its scanned the list once, and only increments by that length, their next withdrawal index will be too low)

If there's less than a set of withdrawals, this gets fun, because your next validator key will be still incremented by the sweep length...

So (0 + 16k) % 5k = 1000 as next_withdrawal_validator_index...

This is covered in the spec, code, but it'd probably be nice to capture that case as a test.

**Comment by ralexstokes** [comment]
I don't exactly understand what you are referring to here...

> network config has 16k validators
> validator minimum is 5k

can you elaborate?

the two cases I see are:
1) validator set is smaller than (or equal to) the sweep length
2) validator set is larger than the sweep length

and both cases are covered here w/ the `minimal` and `mainnet` testing presets e.g. these two tests:

https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/capella/block_processing/test_process_withdrawals.py#L169

https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/capella/block_processing/test_process_withdrawals.py#L188

**Comment by rolfyone** [comment]
Specifically where the validator is smaller than the sweep length and ensuring the next validator index is correctly set when we don't find enough validators...

if there's 100 validators total, and the withdrawal scan length is 120, and we start at index 1 with insufficient withdrawals to process, then the next withdrawal index in the post state needs to be `(1+120) % 100`, and if it's not calculated correctly, the state root will not match...

**Comment by ralexstokes** [comment]
the general pattern of "is `next_withdrawal_validator_index` set correctly?" is checked in all of the spec tests generated from the withdrawal tests in this repo

we have the test case for the specific scenario where the validator set is smaller than the sweep length that I linked to above

the question you are raising now is: can we test for the even more specific scenario where the validator set size is smaller than the sweep length *and also* we have fewer than `MAX_WITHDRAWALS_PER_PAYLOAD` in a block?

and I'd say this doesn't increase the test coverage because:

1. regardless of how many withdrawals end up in a block, we will always be checking that the "next index" is set correctly
2. the `MAX_WITHDRAWALS_PER_PAYLOAD` bound is separate from the sweeping mechanic and we have plenty of other tests to ensure this bound holds

do you think I'm missing something?

**Comment by rolfyone** [comment]
The scenario where there's insufficient validators to match for a payload, and the loop limit is larger than the validator set is specifically interesting because the `next_withdrawal_validator_index` increments by a large amount potentially, and it being incorrect would be supremely bad...

Previously the next index could potentially stay consistent if the loop limit (which was validator size) was reached.  If this code is still in any clients, they may not be aware until this edge case is exercised, which is why i raised the ticket.  The test condition which it exercises I believe is pretty important, because if that `next_withdrawal_validator_index` is not consistent across the board (which in this case involves mod validators.size) then we're in a sticky situation which is not easy to recover from.

so if i have 0 withdrawable validators and 10 total validators, and a loop limit of 13, then you'll end up with this wierd pattern of 
`next_withdrawal_validator_index: 4`
`next_withdrawal_validator_index: 7`
`next_withdrawal_validator_index: 0`
`next_withdrawal_validator_index: 3`

a natural client implementation would be to limit by the min of the validators size OR the loop limit, and it'll just depend how they reconcile the `next_withdrawal_validator_index` at the end, but if they get it wrong this is a scenario that we won't see in current tests I'm pretty sure...

If we feel comfortable that this is enough of an edge case that we need not have a test, then it's not a hill I'm willing to die on, but given it's a chain split if it happens, I figured I'd at least flag it.

**Comment by ralexstokes** [comment]
in this test: https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/capella/block_processing/test_process_withdrawals.py#L169

we have the condition that the size of the validator set is smaller than the sweep limit

and if the concern is correctly setting the `next_withdrawal_validator_index` then I think we would see any bugs if the set of withdrawals is any value between `[0, MAX_WITHDRAWALS_PER_PAYLOAD]` as any deviation will drive a client away from whatever the test computes

so because of that I don't see the value in explicitly testing the scenario where there are 0 withdrawals as any number (which we already have in the linked test) should catch the bug you are describing

**Comment by rolfyone** [comment]
Ok that sounds fair, I've had a quick look and it does seem to test the same kind of scenario, shall i just close this? I think we've also had good test cases on the various network rollouts to show things are functioning correctly now.
