### ISSUE TITLE
Question about LMD-GHOST security proofs fixed by EIP7045

### ISSUE THREAD

**Issue by wenceslas-sanchez** [ethereum/consensus-specs#3453]
*to @djrtwo*

Hi Danny,

I was wondering what are the LMD-GHOST security proofs you are fixing with the [EIP-7045](https://eips.ethereum.org/EIPS/eip-7045) ?

Thanks a lot for your time 👍🏻

**Comment by michaelsproul** [comment]
@wenceslas-sanchez There are some security proofs here, although I'm not sure they cover the attestation range increase exactly (I've only skimmed them): https://notes.ethereum.org/@djrtwo/2023-fork-choice-reorg-disclosure#Proofs

**Comment by wenceslas-sanchez** [comment]
Understood thanks ! 😄

**Comment by potuz** [comment]
The reason to increase the inclusion slot is so that the formal proofs in those notes (and attached files) is actually correct. One of the scenarios is that there is a reorg and the canonical chain cannot be continued because of the necessary attestations in the attacking withheld branch, that are enough to justify a previous epoch, are not possible to include in the canonical branch anymore. This fix makes it always possible for the honest validators to include possibly withheld attestations

**Comment by wenceslas-sanchez** [comment]
Thanks @potuz and @michaelsproul !
